format = """
┌─ $username$hostname:$directory$all$git_branch$git_commit$git_state$git_status
└$character
"""

add_newline = false

[character]
success_symbol = '╼'
error_symbol = '[✗](bold red)'

[username]
style_root = 'bold red'
format = '[$user]($style)'
disabled = false
show_always = true

[hostname]
format = "[@$hostname](blue)"

[directory]
fish_style_pwd_dir_length =  1

[line_break]
disabled = true
