format = """
╭─ $directory$git_branch$git_status $fill $username$hostname$time
╰$character
"""

[fill]
symbol = ' '

[character]
success_symbol = '─'
error_symbol = '[✗](#E84D44)'

[username]
style_user = "fg:#030B16 bg:#06d6a0"
style_root = "fg:red bg:#06d6a0 bold"
disabled = false
show_always = true
format = "[](fg:#06d6a0)[](fg:#030B16 bg:#06d6a0)[$user]($style)[](fg:#06d6a0)"

[hostname]
format = "[](fg:#118ab2)[ $hostname](fg:#030B16 bg:#118ab2)[](fg:#118ab2)"
ssh_only = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '[](fg:#073b4c)[󱑍 $time](fg:#030B16 bg:#073b4c)[](fg:#073b4c)'

[directory]
fish_style_pwd_dir_length = 1
read_only = "󰌾 "
format = "[](fg:#ef476f)[$path](fg:#030B16 bg:#ef476f)[](fg:#ef476f)"

[git_branch]
format = '[](fg:#ffd166)[$symbol$branch(:$remote_branch)](fg:#030B16 bg:#ffd166)'
symbol = " "

[git_status]
format = '[$all_status](fg:#030B16 bg:#ffd166)[](fg:#ffd166)'

[line_break]
disabled = true
