set fish_greeting ''
alias dmesg='dmesg -T'
alias diff='diff --color'
alias egrep='egrep --color'
alias fgrep='fgrep --color'
alias grep='grep --color'
alias ip='ip -c'
alias g='egrep -i'
alias l='ls'
alias l.='ls -ld .*'
alias la='ls -lhA'
alias lk='ls -lhASr'
alias ll='ls -lh'
alias ls='ls --color=auto --group-directories-first'
alias lsb='ls -ail'
alias lt='ls -lhAtr'
alias lx='ls -lhAxb'
alias sudo='sudo '
alias open='gio open'
alias trash='gio trash'
alias tree='tree -C'
alias vi='vim'

set -x  XDG_CONFIG_HOME "$HOME/.config"
set -x  XDG_DATA_HOME "$HOME/.local/share"
set -x  XDG_CACHE_HOME "$HOME/.cache"
